POST http://localhost:9000/Firm/addFirm 
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDFhNTI0ZTA4NTJkMzljZWY3MzcxOCIsImlhdCI6MTc0OTEzMjU5NiwiZXhwIjoxNzQ5MTM2MTk2fQ.96Yl_WvRvRAWPrQmxNuJ-3x3VIYfLyJTiAjOUCaqfjY

{
  "firmname": "BabuRestoBar",
  "area": "GWD",
  "category": ["non-veg", "veg"],
  "region": ["south-india", "north-india"],
  "offer": "10% off",
  "image": "EX.jpg"
}

