POST http://localhost:9000/vender/Register 
Content-Type: application/json

{
  "username": "a",
  "email": "a@gmail.com",
  "password": "1234567891"
}


###
GET http://localhost:9000/vender/ShowAll

###
POST http://localhost:9000/vender/Login
Content-Type: application/json

{
  "email": "a@gmail.com",
  "password":"1234567891"
}