POST http://localhost:9000/Firm/addFirm 
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDgyZjViZGRlMzkwY2EwYTFkNmFmNSIsImlhdCI6MTc0OTU2MTE4OCwiZXhwIjoxNzQ5NTY0Nzg4fQ.4CbTiTy0XcpxDxPB6x_SQAa4H8_yPnbJT4UguXuXaW4

{
  "firmname": "Restaurant",
  "area": "GWD",
  "category": ["non-veg", "veg", "both"],
  "region": ["south-india", "north-india"],
  "image": "EX.jpg"
}

