POST http://localhost:9000/vender/Register 
Content-Type: application/json

{
  "username": "b",
  "email": "b@gmail.com",
  "password": "1234567891"
}


###
GET http://localhost:9000/vender/ShowAll

###
POST http://localhost:9000/vender/Login
Content-Type: application/json

{
  "email": "b@gmail.com",
  "password":"1234567891"
}

###
GET http://localhost:9000/vender/AllVendors

###
GET http://localhost:9000/vender/getVendorById/68482f5bdde390ca0a1d6af5